### PR TITLE
[for bug reproduction] config with isolated and npm

### PR DESCRIPTION
**Pull request by arnaudambro**
when running `npm i && npm run dev` within `examples/pwa-simple-pw` I get this error

```
[vite] Internal server error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'virtual:'
      at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
      at defaultLoad (node:internal/modules/esm/load:130:3)
      at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
      at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
      at new ModuleJob (node:internal/modules/esm/module_job:65:26)
      at #createModuleJob (node:internal/modules/esm/loader:303:17)
      at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
      at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:21) (x3)
```

I'll open an issue in parallel

### CODE REVIEW

**Comment by userquin** [comment]
This is a pnpm monorepo, to run the examples you need to install depedencies from root folder using pnpm.

**Comment by userquin** [comment]
You can use create-pwa for a remix example, check https://vite-pwa-org.netlify.app/guide/scaffolding.html

Select react then remix in the prompt...

**Comment by arnaudambro** [comment]
I know, and I'd like to know if it's possible to do differently: why wouldn't make the `examples` independent from any package manager ? yarn, npm, pnpm, whatever ?

cause many people don't use `pnpm` and your examples' codebases are VERY useful... but I wish they could help me even more: if the configuration allowed to have any package manager running the examples, I could better understand what is the diff between MY project and YOUR example, and fix the bug I have in my project. which is the same bug here

thanks !

**Comment by arnaudambro** [comment]
> You can use create-pwa for a remix example, check https://vite-pwa-org.netlify.app/guide/scaffolding.html
> 
> Select react then remix in the prompts...

didn't see your message

I'll try that thanks

**Pull request closed without merging**
